### ISSUE TITLE
make sure to comment main parts of code

### ISSUE THREAD

**Issue by ad3429** [gmjones/prj-rev-bwfs-dasmoto#1]
https://github.com/gmjones/prj-rev-bwfs-dasmoto/blob/master/DasmotosWebsite/index.html#L7-L27

Make sure to comment the main parts of your HTML in future projects. This becomes increasingly important as your projects become larger and more complex. Here is a quick refresher on commenting in HTML:

<img width="197" alt="html_comment" src="https://user-images.githubusercontent.com/25671399/29489315-fb8f7514-84eb-11e7-9fd3-3f38e93b47d1.png">

**Comment by gmjones** [comment]
Hi - Thanks for the feedback. I appreciate that it is good practice to add comments across both the HTML and CSS but wasn't really sure what the best practise was in terms of what should/shouldn't be commented on. Any advice you can give on this would be much appreciated!

**Comment by ad3429** [comment]
Hey @gmjones, great question. Usually you don't want to comment excessively since this can be distracting, but it is good to comment the main parts that you believe to be significant. For example, in your HTML file, there are 3 main sections to your webpage (Brushes, Frames and Paint) so it would be a good idea to comment where those sections are exactly in your code. Something as simple as this would suffice:

<img width="546" alt="screen shot 2017-08-19 at 2 51 59 pm" src="https://user-images.githubusercontent.com/25671399/29489396-385c4844-84ee-11e7-8d6a-8b0fc9b3bdf8.png">

**Comment by gmjones** [comment]
great that's a big help - do you have any recommendations for the CSS in this case - there is not much of it so wasn't sure what it needed?

**Comment by ad3429** [comment]
Yeah, you wouldn't need much commenting in your CSS for this one since there isn't much code, but it's still good to get in the practice of commenting for when your projects become much larger. Here is an example of how you could have commented your CSS:

<img width="436" alt="screen shot 2017-08-19 at 3 49 16 pm" src="https://user-images.githubusercontent.com/25671399/29489754-2f8d7bc2-84f6-11e7-97c2-db832f3f8b13.png">
